# Generated by Django 6.0 on 2025-12-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
