# Generated by Django 6.0 on 2025-12-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.TextField(blank=True, null=True),
        ),
    ]
